### ISSUE TITLE
Lenovo update URLs

### ISSUE THREAD

**Issue by flcdrg** [flcdrg/chocolatey-lenovo-thinkvantage-system-update#3]
See if these URLs can be used to detect updated application:

- https://download.lenovo.com/ibmdl/pub/pc/pccbbs/agent/SSClientCommon/HelloLevel_9_34_00.xml
- https://download.lenovo.com/catalog//30AK_Win10_DESC.xml
- https://download.lenovo.com/catalog//30AK_Win10.xml
- https://download.lenovo.com/pccbbs/thinkcentre_drivers/k2vdo26us14_2_.xml

**Comment by ghost** [comment]
The driver catalog XMLs do not seem to contain links to System Update itself (except for a "Hotfix for Lenovo System Update").

sclexman described the HELLO LEVEL update mechanism [here](https://forums.lenovo.com/t5/Pre-Installed-Lenovo-Software/Is-this-System-Update-message-legit/m-p/3857185/highlight/true#M31600). So using any smaller HELLO LEVEL value would return a valid XML, e.g. [HelloLevel_9_**01**_00](https://download.lenovo.com/ibmdl/pub/pc/pccbbs/agent/SSClientCommon/HelloLevel_9_01_00.xml) or [HelloLevel_9_**33**_00](https://download.lenovo.com/ibmdl/pub/pc/pccbbs/agent/SSClientCommon/HelloLevel_9_33_00.xml), with the latest Version value to substitute into the download link.
`https://download.lenovo.com/pccbbs/thinkvantage_en/systemupdate{Version}.exe`

It also appears that the HELLO LEVEL pages have not been updated for the latest version (5.07.0072 should correspond to HelloLevel_9_**35**_00)

**Comment by flcdrg** [comment]
Link to other documents

Lenovo System Update for Windows 10 (32-bit, 64-bit), 8.1 (32-bit, 64-bit), 8 (32-bit, 64-bit), 7 (32-bit, 64-bit) - Desktop, Notebook, Workstation - 5.07.0078, 28 Feb 2019
https://support.lenovo.com/au/en/downloads/ds012808

readme.txt - https://download.lenovo.com/pccbbs/thinkvantage_en/systemupdate5.07.0078.txt
